# Generated by Django 5.0.6 on 2024-06-06 14:22

import uuid
import votbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('perv_hash', models.CharField(blank=True, max_length=100)),
                ('merkle_hash', models.CharField(blank=True, max_length=100)),
                ('self_hash', models.CharField(blank=True, max_length=100)),
                ('nonce', models.IntegerField(null=True)),
                ('timestamp', models.FloatField(default=votbase.models.get_time)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('criminal_records', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vote', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=votbase.models.get_time)),
                ('block_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote_Auth',
            fields=[
                ('username', models.CharField(default='admin', max_length=100, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('result_Calculated', models.BooleanField(default=False)),
                ('perv_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_key_n', models.CharField(max_length=100)),
                ('public_key_e', models.IntegerField(max_length=100)),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voter_List',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voter_Pvt',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=100)),
                ('public_key_n', models.CharField(max_length=100)),
                ('public_key_d', models.CharField(max_length=100)),
            ],
        ),
    ]
