# Generated by Django 5.0.6 on 2024-06-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_to_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votbase.candidate'),
        ),
    ]
