# Generated by Django 5.0.6 on 2024-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='public_key_e',
            field=models.CharField(max_length=100),
        ),
    ]
