# Generated by Django 5.0.6 on 2024-06-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0002_alter_vote_vote_to_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='votercrypto',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='votercrypto',
            name='vote',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
