# Generated by Django 5.0.6 on 2024-07-02 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0002_block_new'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block_new',
            new_name='Block_old',
        ),
    ]
