# Generated by Django 5.0.6 on 2024-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0002_alter_voter_public_key_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='public_key_e',
            field=models.IntegerField(default=0),
        ),
    ]
