# Generated by Django 5.0.6 on 2024-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0003_votercrypto_password_votercrypto_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votercrypto',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='votercrypto',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
