# Generated by Django 5.0.6 on 2024-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0004_rename_name_votercrypto_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
