# Generated by Django 5.0.6 on 2024-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0004_alter_voter_public_key_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='public_key_n',
            field=models.CharField(max_length=100),
        ),
    ]
