# Generated by Django 5.0.6 on 2024-07-02 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0004_delete_block_old'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='Block_new',
        ),
    ]
