# Generated by Django 5.0.6 on 2024-06-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0005_candidate_gender_candidate_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='count',
        ),
        migrations.RemoveField(
            model_name='votercrypto',
            name='password',
        ),
        migrations.RemoveField(
            model_name='votercrypto',
            name='vote',
        ),
    ]
