# Generated by Django 5.0.6 on 2024-06-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0005_alter_voter_public_key_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profession',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
