# Generated by Django 5.0.6 on 2024-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0006_remove_candidate_count_remove_votercrypto_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='VoteAuth',
        ),
        migrations.DeleteModel(
            name='VoterCrypto',
        ),
        migrations.DeleteModel(
            name='VoterList',
        ),
        migrations.AddField(
            model_name='candidate',
            name='encrypted_data',
            field=models.TextField(default=None),
        ),
    ]
