# Generated by Django 5.0.6 on 2024-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0007_delete_block_delete_voteauth_delete_votercrypto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='encrypted_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
