# Generated by Django 5.0.6 on 2024-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0009_remove_candidate_encrypted_data_remove_vote_block_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MerkleTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_hash', models.CharField(max_length=64)),
                ('blocks', models.ManyToManyField(to='votbase.block')),
            ],
        ),
    ]
