# Generated by Django 5.0.6 on 2024-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0011_alter_block_data_alter_block_hash_alter_block_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merkletree',
            name='blocks',
            field=models.ManyToManyField(blank=True, null=True, to='votbase.block'),
        ),
        migrations.AlterField(
            model_name='merkletree',
            name='root_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
