# Generated by Django 5.0.6 on 2024-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0012_alter_merkletree_blocks_alter_merkletree_root_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='encrypted_data',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
