# Generated by Django 5.0.6 on 2024-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0014_alter_block_data_alter_block_hash_alter_block_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='encrypted_data',
            field=models.CharField(blank=True, default=0, max_length=64, null=True),
        ),
    ]
