# Generated by Django 5.0.6 on 2024-06-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0022_alter_candidate_encrypted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='encrypted_data',
            field=models.CharField(blank=True, default='some string', max_length=64),
        ),
    ]
