# Generated by Django 5.0.6 on 2024-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0034_alter_candidate_encrypted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merkletree',
            name='blocks',
            field=models.ManyToManyField(default=0, to='votbase.block'),
        ),
    ]
