# Generated by Django 5.0.6 on 2024-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0036_alter_block_index_alter_merkletree_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(max_length=64),
        ),
    ]
