# Generated by Django 5.0.6 on 2024-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votbase', '0037_alter_block_data_alter_block_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merkletree',
            name='root_hash',
            field=models.CharField(max_length=64),
        ),
    ]
